name: zero-project-apis-stg
namespace: urbi
replicaCount: 1

image: registry.momrah.gov.sa/urbi-omar/zero-project-apis:stg
containerPort: 80
servicePort: 80
serviceType: ClusterIP

appVersion: staging

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "50m"
    memory: "128Mi"

ingress:
  name: be-zero-project-apis-stg
  className: urbi
  host: zero-project-stg.momah.gov.sa
  path: /api/(.*)
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
