apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-dev
  namespace: urbi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dev
  namespace: urbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-dev
  template:
    metadata:
      labels:
        app: mongo-dev
    spec:
      containers:
        - name: mongo-dev
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "CityViewGPT-DB"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc-dev
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-dev
  namespace: urbi
spec:
  type: ClusterIP
  selector:
    app: mongo-dev
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
