name: momtathel-upliftment-cis-ui
namespace: urbi
replicaCount: 3

image: registry.momrah.gov.sa/urbi-omar/momtathel-upliftment-ui-cis-prod:v0.003
containerPort: 80
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "1024Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

env:
  - name: REACT_APP_BASE_URL
    value: https://upliftment-cis.momah.gov.sa
  - name: REACT_APP_MAP_KEY
    value: 28ed92f1-de4b-4060-b159-2dc19e9b8bf5

ingress:
  name: be-momtathel-upliftment-cis-ui
  host: upliftment-cis.momah.gov.sa
  corsAllowHeaders: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token
  paths:
    - path: /
      pathType: ImplementationSpecific

