name: zero-project-etl-pipeline
namespace: urbi

image: registry.momrah.gov.sa/urbi-omar/zero-project-etl-pipeline:latest

cronjob:
  schedule: "0 2 * * *"   # set when you want scheduled runs (e.g. 02:00 daily)
  suspend: true           # true = no schedule, run manually only

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "256Mi"
