
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoserver-ingress
  namespace: urbi
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /geoserver/$2
spec:
  ingressClassName: urbi
  rules:
  - host: urbi-lifestyle-stg.momrah.gov.sa
    http:
      paths:
      - path: /geoserver(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: geoserver-service
            port:
              number: 80


