
apiVersion: v1
kind: Service
metadata:
  name: geoserver-service
  namespace: urbi
spec:
  type: ClusterIP
  selector:
    app: geoserver
  ports:
    - name: http
      port: 80
      targetPort: 8080
