name: cityview-frames-api
namespace: urbi
replicaCount: 1
appVersion: v1.0.0

image: registry.momrah.gov.sa/urbi-omar/cityview-frames-api:v1.0.0
imagePullPolicy: IfNotPresent
containerPort: 5000
servicePort: 80
serviceType: ClusterIP

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"

# Ingress configuration for staging
ingress:
  name: be-cityview-frames-api
  className: urbi
  host: cityview-stg.momah.gov.sa

  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

  # Path rules
  paths:
    - path: /frames-api(/.*)
      pathType: ImplementationSpecific
