apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-notifications-ui
  namespace: urbi
  labels:
    app.kubernetes.io/instance: rbac-notifications-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rbac-notifications-ui
    app.kubernetes.io/version: staging
    helm.sh/chart: rbac-notifications-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rbac-notifications-ui
      app.kubernetes.io/name: rbac-notifications-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rbac-notifications-ui
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: rbac-notifications-ui
        app.kubernetes.io/version: staging
        helm.sh/chart: rbac-notifications-ui
    spec:
      containers:
        - name: rbac-notifications-ui
          image: registry.momrah.gov.sa/urbi-omar/rbac-notifications-ui-stg:v0.1.3
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
