apiVersion: v1
kind: Service
metadata:
  name: rbac-notifications-ui
  namespace: urbi
  labels:
    app.kubernetes.io/instance: rbac-notifications-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rbac-notifications-ui
    app.kubernetes.io/version: staging
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/instance: rbac-notifications-ui
    app.kubernetes.io/name: rbac-notifications-ui
