apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbac-notifications-api
  namespace: urbi
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    # REMOVE these two lines:
    nginx.ingress.kubernetes.io/rewrite-target: /$2/
    nginx.ingress.kubernetes.io/use-regex: "true"
    #new annotation 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "socketio_affinity"

spec:
  ingressClassName: urbi
  rules:
  - host: baladyeye-stg.momah.gov.sa
    http:
      paths:
      - path: /notifications-api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: rbac-notifications-api
            port:
              number: 80
  tls:
  - hosts:
    - baladyeye-stg.momah.gov.sa
