apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: be-cityview-users-activity
  namespace: urbi
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,x-share-token"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: urbi
  rules:
    - host: cityview-pro-api.momah.gov.sa
      http:
        paths:
          - path: /user-activity(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cityview-users-activity
                port:
                  number: 80
  tls:
    - hosts:
        - cityview-pro-api.momah.gov.sa
      # secretName: <existing-tls-secret-if-required>
