apiVersion: v1
kind: Service
metadata:
  name: cityview-users-activity
  namespace: urbi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: cityview-users-activity
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
