apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  BY_ID_URL: {{ .Values.env.BY_ID_URL }}
  AI_URL: {{ .Values.env.AI_URL }}
  AI_MARKERS_URL: {{ .Values.env.AI_MARKERS_URL }}
  AI_SUGGEST_URL: {{ .Values.env.AI_SUGGEST_URL }}
  DEFAULT_PLACES_FORWARD_URL: {{ .Values.env.DEFAULT_PLACES_FORWARD_URL }}
  DEFAULT_MARKERS_FORWARD_URL: {{ .Values.env.DEFAULT_MARKERS_FORWARD_URL }}
  DEFAULT_PLACES_FORWARD_URL_BYID: {{ .Values.env.DEFAULT_PLACES_FORWARD_URL_BYID }}
  DEFAULT_SUGGESTS_FORWARD_URL: {{ .Values.env.DEFAULT_SUGGESTS_FORWARD_URL }}
  RCMC_AREA_URL: {{ .Values.env.RCMC_AREA_URL }}
  BY_CATEGORY_URL: {{ .Values.env.BY_CATEGORY_URL }}
  REGION_ID_URL: {{ .Values.env.REGION_ID_URL }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL }}
  PORT: "{{ .Values.env.PORT }}"
  REDIS_CACHE: "{{ .Values.env.REDIS_CACHE }}"
  REDIS_HOSTNAME: {{ .Values.env.REDIS_HOSTNAME }}
  REDIS_PORT: "{{ .Values.env.REDIS_PORT }}"
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD }}
  REDIS_USERNAME: {{ .Values.env.REDIS_USERNAME }}
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS }}
  KAFKA_USERNAME: {{ .Values.env.KAFKA_USERNAME }}
  KAFKA_TOPIC: {{ .Values.env.KAFKA_TOPIC }}
  DISCREPANCY_API: {{ .Values.env.DISCREPANCY_API }}
  AI_URL_01: {{ .Values.env.AI_URL_01 }}
  AI_MARKERS_URL_01: {{ .Values.env.AI_MARKERS_URL_01 }}
  AI_SUGGEST_URL_01: {{ .Values.env.AI_SUGGEST_URL_01 }}
  AI_URL_02: {{ .Values.env.AI_URL_02 }}
  AI_MARKERS_URL_02: {{ .Values.env.AI_MARKERS_URL_02 }}
  AI_SUGGEST_URL_02: {{ .Values.env.AI_SUGGEST_URL_02 }}
  WEIGHT_01: "{{ .Values.env.WEIGHT_01 }}"
  WEIGHT_02: "{{ .Values.env.WEIGHT_02 }}"

 
  #data:
  #BY_ID_URL: {{ quote .Values.env.BY_ID_URL }}
  #AI_URL_02: {{ quote .Values.env.AI_URL_02 }}
  #AI_MARKERS_URL_02: {{ quote .Values.env.AI_MARKERS_URL_02 }}
  #AI_MARKERS_URL_01: {{ quote .Values.env.AI_MARKERS_URL_01 }}
  #AI_SUGGEST_URL_01: {{ quote .Values.env.AI_SUGGEST_URL_01 }}
  #AI_URL_01: {{ quote .Values.env.AI_URL_01 }}
  #DEFAULT_PLACES_FORWARD_URL: {{ quote .Values.env.DEFAULT_PLACES_FORWARD_URL }}
  #DEFAULT_MARKERS_FORWARD_URL: {{ quote .Values.env.DEFAULT_MARKERS_FORWARD_URL }}
  #DEFAULT_PLACES_FORWARD_URL_BYID: {{ quote .Values.env.DEFAULT_PLACES_FORWARD_URL_BYID }}
  #DEFAULT_SUGGESTS_FORWARD_URL: {{ quote .Values.env.DEFAULT_SUGGESTS_FORWARD_URL }}
  #AI_SUGGEST_URL_02: {{ quote .Values.env.AI_SUGGEST_URL_02 }}
  #AI_PLACES_GOOGLE_URL: {{ quote .Values.env.AI_PLACES_GOOGLE_URL }}
  #AI_MARKERS_GOOGLE_URL: {{ quote .Values.env.AI_MARKERS_GOOGLE_URL }}
  #AI_GOOGLE_URL_BYID: {{ quote .Values.env.AI_GOOGLE_URL_BYID }}
  #RCMC_AREA_URL: {{ quote .Values.env.RCMC_AREA_URL }}
  #BY_CATEGORY_URL: {{ quote .Values.env.BY_CATEGORY_URL }}
  #REGION_ID_URL: {{ quote .Values.env.REGION_ID_URL }}
  #LOG_LEVEL: {{ quote .Values.env.LOG_LEVEL }}
  #PORT: {{ quote .Values.env.PORT }}
  #REDIS_CACHE: {{ quote .Values.env.REDIS_CACHE }}
  #REDIS_HOSTNAME: {{ quote .Values.env.REDIS_HOSTNAME }}
  #REDIS_PORT: {{ quote .Values.env.REDIS_PORT }}
  #REDIS_USERNAME: {{ quote .Values.env.REDIS_USERNAME }}
  #KAFKA_BROKERS: {{ quote .Values.env.KAFKA_BROKERS }}
  #KAFKA_USERNAME: {{ quote .Values.env.KAFKA_USERNAME }}
  #KAFKA_TOPIC: {{ quote .Values.env.KAFKA_TOPIC }}
  #DISCREPANCY_API: {{ quote .Values.env.DISCREPANCY_API }}
  #AI_URL: {{ quote .Values.env.AI_URL }}
  #AI_MARKERS_URL: {{  quote .Values.env.AI_MARKERS_URL }}
  #AI_SUGGEST_URL: {{ quote .Values.env.AI_SUGGEST_URL }}
  #WEIGHT_01: {{ quote .Values.env.WEIGHT_01 }}
  #WEIGHT_02: {{ quote .Values.env.WEIGHT_02 }}

