apiVersion: v1
kind: Service
metadata:
  name: cityview-ai-prod
  namespace: urbi
  labels:
    app.kubernetes.io/instance: cityview-ai-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cityview-ai-prod
    app.kubernetes.io/version: development
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: cityview-ai-prod
    app.kubernetes.io/name: cityview-ai-prod

