apiVersion: v1
kind: Service
metadata:
  name: kibana-proxy
  namespace: urbi
spec:
  type: ExternalName
  # This points to the real service in the 'kibana' namespace
  externalName: kibana-kibana.kibana.svc.cluster.local
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
