# 1. Connect to internal HAProxy
elasticsearchHosts: "http://haproxy.urbi.svc.cluster.local:9200"

# 2. Service Settings
service:
  type: ClusterIP
  port: 5601

# 3. Force the 8.17.1 Image
image: "docker.elastic.co/kibana/kibana"
imageTag: "8.17.1"

# 4. Resources
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

# 5. Disable hooks (Since we created the secret manually)
migration:
  enabled: false

# 6. Disable SSL
elasticsearch:
  ssl:
    enabled: false
