apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-mcp
  namespace: urbi
  labels:
    app.kubernetes.io/instance: jira-mcp
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: jira-mcp
    app.kubernetes.io/version: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jira-mcp
      app.kubernetes.io/name: jira-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: jira-mcp
        app.kubernetes.io/name: jira-mcp
    spec:
      containers:
        - name: jira-mcp
          image: registry.momrah.gov.sa/urbi-omar/jira-mcp:v0.6.6
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: NOTIFICATIONS_BASE_URL
              value: "http://rbac-notifications-api.urbi.svc.cluster.local:80"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always

