apiVersion: v1
kind: Service
metadata:
  name: jira-mcp
  namespace: urbi
  labels:
    app.kubernetes.io/instance: jira-mcp
    app.kubernetes.io/name: jira-mcp
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: jira-mcp
