apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-webapp-biban25
  namespace: urbi
  labels:
    app.kubernetes.io/instance: events-webapp-biban25
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: events-webapp-biban25
    app.kubernetes.io/version: production
    helm.sh/chart: events-webapp-biban25-0.1.0
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: events-webapp-biban25
      app.kubernetes.io/name: events-webapp-biban25
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: events-webapp-biban25
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: events-webapp-biban25
        app.kubernetes.io/version: production
        helm.sh/chart: events-webapp-biban25-0.1.0
    spec:
      containers:
        - name: events-webapp-biban25
          image: registry.momrah.gov.sa/urbi-omar/events-webapp-biban25-prod:v1.2.3
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /biban25/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /biban25/
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
