apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: {{ .Values.appVersion | default "production" }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
