name: dqp-pull-tasks
namespace: urbi

image: registry.momrah.gov.sa/urbi-omar/dqp-pull-task-stg:v0.003

resources:
  limits:
    cpu: "1"
    memory: "1024Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"


cronjob:
  enabled: true
  schedule: "0 * * * *"

